name: codeceptjs-web-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
          npm install
          npx playwright install
          npx codeceptjs run --plugins allure
    
    - name: Load test report history
    - uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

    - name: Build test report
    - uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

    - name: Publish test report
    - uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: $
          publish_branch: gh-pages
          publish_dir: allure-history